export type User = {
  id: String;
  firstName: String;
  lastName: String;
  usualName: String;
  birthName: String;
  email: String;
  phone: String;
  address: String;
  zipCode: String;
  city: String;
  country: String;
  bloodType: String;
  nationality: String;
  rhesus: String;
  birthDate: String;
  birthPlace: String;
  weight: number;
  size: number;
  emergencyPeople: any[];
  socialSecurityNumber: String;
};
